---
title: "Otus centrales de tomate según muestras divididas"
output: html_document
date: '2023-09-27'
---


```{r}

if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
if (!require(vegan)) install.packages('vegan')
library(vegan)
if (!require(igraph)) install.packages('igraph')
library(igraph)
if (!require(apcluster)) install.packages('apcluster')
library(apcluster)
if (!require(plyr)) install.packages('plyr')
library(plyr)
if (!require(stringr)) install.packages('stringr')
library(stringr)
if (!require(phyloseq)) install.packages('phyloseq')
library(phyloseq)

```


#Muestras divididas según desarrollo o no


```{r}
muestras_tomate <- c("desarrollo" , "no_desarrollo" , "totales")
```

```{r}
otus_tomate_desarrollo <- read.csv("../central_otus/otus_centrales_tomate_desarrollo" , row.names = 1)
otus_tomate_no_desarrollo <- read.csv("../central_otus/otus_centrales_tomate_no_desarrollo.csv" , row.names = 1)
otus_tomate_totales <- read.csv("../central_otus/reporte_tomate1.csv" , row.names = 1)

otus_centrales_tomate2 <- list(otus_tomate_desarrollo , otus_tomate_no_desarrollo , otus_tomate_totales)
```
```{r}
rizosfera <- import_biom("../../data/biom/tomate.txt_9.biom")
```

```{r}
taxa_centrales_tomate <- list()
for (i in 1:3){
  taxa_centrales_tomate[[i]] <- rizosfera@tax_table@.Data[row.names(otus_centrales_tomate2[[i]]),]
  print( paste0( "Se obtuvieron "  , length(row.names(otus_centrales_tomate2[[i]])) , " OTUs centrales en las muestras de " , muestras_tomate[i] ) )
}

```


```{r}
pares <- list(c(1,2) , c(1,3) , c(2,3))
for (i in 1:3){
  print(intersect(as.vector(taxa_centrales_tomate[[pares[[i]][1]]][ , "Rank5"]) , as.vector(taxa_centrales_tomate[[pares[[i]][2]]][ , "Rank5"]) ))
}
```

```{r}
pares <- list(c(1,2) , c(1,3) , c(2,3))
for (i in 1:3){
  print(intersect(as.vector(taxa_centrales_tomate[[pares[[i]][1]]][ , "Rank6"]) , as.vector(taxa_centrales_tomate[[pares[[i]][2]]][ , "Rank6"]) ))
}
```

```{r}
pares <- list(c(1,2) , c(1,3) , c(2,3))
for (i in 1:3){
  print(intersect(as.vector(taxa_centrales_tomate[[pares[[i]][1]]][ , "Rank7"]) , as.vector(taxa_centrales_tomate[[pares[[i]][2]]][ , "Rank7"]) ))
}
```

Entre las principales coincidencias entre los diversos Otus centrales de rizósfera de tomate se encuentran la abundancia del género Pseudomonas y la presencia de especies del género Candidatus.

```{r}
print(taxa_centrales_tomate[[1]][ , c( "Rank7")])
```
```{r}
print(taxa_centrales_tomate[[2]][ , c( "Rank7")])
```


```{r}
data_tomate_desarrollo <- read.csv("../../data/tables/tomate_desarrollo.csv" , row.names = 1, header = TRUE )

medias <- c()
medianas <- c()
for (i in 1:dim(data_tomate_desarrollo)[2]){
  medias <- c(medias , mean(data_tomate_desarrollo[ , i]))
  medianas <- c(medianas , median(data_tomate_desarrollo[ , i]))
  }

data_tomate_desarrollo <- data_tomate_desarrollo[ row.names(otus_centrales_tomate2[[1]]),]
data_tomate_desarrollo <- rbind(medias , data_tomate_desarrollo)
data_tomate_desarrollo <- rbind(medianas , data_tomate_desarrollo)

row.names(data_tomate_desarrollo) <- c("Medianas" , "Medias" , row.names(otus_centrales_tomate2[[1]]))
head(data_tomate_desarrollo)
```

```{r}
data_tomate_no_desarrollo <- read.csv("../../data/tables/tomate_no_desarrollo.csv" , row.names = 1, header = TRUE )

medias <- c()
medianas <- c()
for (i in 1:dim(data_tomate_no_desarrollo)[2]){
  medias <- c(medias , mean(data_tomate_no_desarrollo[ , i]))
  medianas <- c(medianas , median(data_tomate_no_desarrollo[ , i]))
  }

data_tomate_no_desarrollo <- data_tomate_no_desarrollo[ row.names(otus_centrales_tomate2[[2]]),]
data_tomate_no_desarrollo <- rbind(medias , data_tomate_no_desarrollo)
data_tomate_no_desarrollo <- rbind(medianas , data_tomate_no_desarrollo)

row.names(data_tomate_no_desarrollo) <- c("Medianas" , "Medias" , row.names(otus_centrales_tomate2[[2]]))
head(data_tomate_no_desarrollo)
```


#Otus centrales según submuestreos aleatorios 

```{r}
otus_tomate_aleatorio1 <- list()

for (i in 1:4){
  otus_tomate_aleatorio1[[i]] <- read.csv( paste0("../central_otus/otus_centrales_tomate_aleatorio1_" , as.character(i) , ".csv" ) , row.names = 1)
}
```

```{r}
taxa_tomate_aleatorio1 <- list()
for (i in 1:4){
  taxa_tomate_aleatorio1[[i]] <- rizosfera@tax_table@.Data[row.names(otus_tomate_aleatorio1 [[i]]),]
  print( paste0( "Se obtuvieron "  , length(row.names(otus_tomate_aleatorio1[[i]])) , " OTUs centrales en el submuestreo aleatorio " , as.character(i)  ) )
}

```


```{r}
pares <- list(c(1,2) , c(1,3) ,c(1,4) , c(2,3) , c(2,4), c(3,4))
for (i in 1:6){
  print(intersect(as.vector(taxa_tomate_aleatorio1[[pares[[i]][1]]][ , "Rank5"]) , as.vector(taxa_tomate_aleatorio1[[pares[[i]][2]]][ , "Rank5"]) ))
}
```


```{r}
pares <- list(c(1,2) , c(1,3) ,c(1,4) , c(2,3) , c(2,4), c(3,4))
for (i in 1:6){
  print(intersect(as.vector(taxa_tomate_aleatorio1[[pares[[i]][1]]][ , "Rank6"]) , as.vector(taxa_tomate_aleatorio1[[pares[[i]][2]]][ , "Rank6"]) ))
}
```


```{r}
pares <- list(c(1,2) , c(1,3) ,c(1,4) , c(2,3) , c(2,4), c(3,4))
for (i in 1:6){
  print(intersect(as.vector(taxa_tomate_aleatorio1[[pares[[i]][1]]][ , "Rank7"]) , as.vector(taxa_tomate_aleatorio1[[pares[[i]][2]]][ , "Rank7"]) ))
}
```

```{r}
for (i in 1:4){
  print(intersect(as.vector(taxa_tomate_aleatorio1[[i]][ , "Rank6"]) , as.vector(taxa_centrales_tomate[[3]][ , "Rank6"]  ) ))
}
```


```{r}
for (i in 1:4){
  print(intersect(as.vector(taxa_tomate_aleatorio1[[i]][ , "Rank7"]) , as.vector(taxa_centrales_tomate[[3]][ , "Rank7"]  ) ))
}
```










```{r}
red_tomate_desarrollo <- read.csv("../../data/networks/tomate_desarrollo_species_raw_network.csv")


red_tomate_no_desarrollo <- read.csv("../../data/networks/tomate_no_desarrollo_species_raw_network.csv")

redes <- list(red_tomate_desarrollo , red_tomate_no_desarrollo)
```



```{r}
V(redes[[1]])$label <- NA
V(redes[[1]])$size <- 3
plot(redes[[1]])
```



```{r}
nombres_otus_centrales_maiz <- as.character(otus_centrales[[3]][,"nodos"])
red_otus_centrales_maiz <- induced_subgraph(redes[[3]], nombres_otus_centrales_maiz  ,"auto")
print( otus_centrales[[3]][,"nodos"])

print(row.names(otus_centrales[[3]]))
print(degree( red_otus_centrales_maiz))
#V(net_work_centrales)$label <- tax_centrales[,"Rank7"]
```



```{r}
plot(red_otus_centrales_maiz)

```









