---
title: "keystone_fontove_auc_permanova"
output: html_document
date: '2022-10-03'
---
#Datos
##Muestras 

```{r}
getwd()
setwd("~/proyecto/redes_correlacion_coocurrencia")

#Se cargan los datos de las muestras
data <- read.table("table.from_chile.txt", row.names = 1, header = FALSE , sep= "" )

#Se agrega una columna que a cada otu asigna la etiqueta correspondiente en la red
data$nodos <- 0:(dim(data)[1]-1)


#Dado que hay varios otus solo presentes en una muestra, y tienen por lo tanto grado artificialmente alto, dichos otus son descartados. Esta filtración puede modificarse para descartar otus presentes en a lo más otra cota de muestras

#Se crea el vector que escogerá los otus en más de una 
filt <- c()
for (i in 1:dim(data)[1]) {
  #nos concentramos en las columnas referentes a las muestras
  v_i <- as.vector(data[i,1:7])
  #el siguiente 1 es filtro
  if (length(v_i [ v_i > 0 ]) > 1 ) {
    filt <- c(filt, i)
  }
}

data <- data[filt,]

head(data)
dim(data)
```

##Separación de las muestras por metadatos

```{r}
#La separación es por etapa fenológica; los siguientes vectores describen qué muestras corresponden a cada etapa
#produccion <- c("V2")
#plantacion <- c("V8")
desarrollo <- c("V3", "V4", "V5" ,"V6")

no_des <- c("V2", "V7", "V8")

grupos <- list()
grupos[[1]] <- desarrollo
grupos[[2]] <- no_des
#data_prod <- data[,produccion]
#data_plan <- data[,plantacion]
#data_des <- data[,desarrollo]

```


```{r}
library(vegan)
bc_dist <- vegdist(t(data[,1:7]), method = "bray")
bc_dist
PCoA <- cmdscale(bc_dist, eig = TRUE, k = 2)
PCoA
plot(PCoA$points,las = 1, cex.lab = 1.5, pch = 16)
```





##Data frame que representa la red y vector de nodos(otus)

```{r}
#Se carga la red
red <- read.csv("networks/chile_species_raw_network.csv")
red = red[,1:3]

#Dado que se han filtrado otus, solo retendremos las aristas que se refieren a los otus conservados en nuestros datos
edges <- c()
for (i in 1:dim(red)[1]) {
  if (is.element(red[i,1], data$nodos) && is.element(red[i,2], data$nodos )  ){
    edges <- c(edges , i)
  }
}

red <- red[edges, ]

head(red)
dim(red)
```
##Cálculo de medidas de centralidad


```{r}

#Esta función calcula el área bajo la curva de una función representada como un dataframe, donde la columna 1 es el dominio, y sus imágenes están en la columna 2. Las variables están escritas como grados, pero se espera usar con otras medidas de centralidad. 
auc <- function(df_deg){
  sm_p <- 0
  for (i in 1:dim(df_deg)[1]) {
  f_i = df_deg[i,dim(df_deg)[2]]
  if (f_i >= 0){sm_p = sm_p + f_i}
  #de momento solo se sumarán grados o fuerzas positivas
  #else{sm_p = sm_p - f_i}
}

return(sm_p)}
```

```{r}
#Con un dataframe que represente una función, y una cota superior (se espera que sea una fracción del área bajo la curva de dicha funcion). Nos devuelve la cantidad de "otus", como están ordenados según el dataframe, que alcanzan dicha cota.
auc_percent <- function(df_deg, propo){
  i <- 1
  sum_par <- 0
  #c <- c() 
  while(i <= dim(df_deg)[1] && sum_par < propo) {
    #c <- c(c,i)
    g_i = df_deg[i,dim(df_deg)[2]]
    sum_par = sum_par + g_i
    i = i+1
  }
  return(i-1)
}
```





#Grado



```{r}

# Dar un Otu numerico
# variables son un OTU y un dataframe (red)
# red tiene tres columnas, dos de otus y una de coeficente
# funcion Ogrado_TOU_en_df

deg_otu <- function(df , otu){
  
  x_1 <- 1
  suma_otu <- 0
  
  while (x_1 <= dim(df)[1] && df[x_1, 1] != otu ){x_1 = x_1 + 1}
  
 
  
  while (x_1 <= dim(df)[1] && df[x_1 ,1] == otu ){ suma_otu = suma_otu + df[x_1 ,3]
  
  x_1 = x_1 + 1}
  
return(suma_otu)}
```

```{r}

deg <- function(df , nodes){
  #df debe ser un data frame cuyas primeras dos columnas representan los pares de otus, sin redundancias, y la tercera es el peso de la arista
  #nodes es el vector de etiquetas ordenadas de los otus, y con cuyo orden se pueda ordenar las primeras dos columnas de df
  #ejemplo de juguete con una red binaria (K_{2,3})
  
  #nodes_toy <- c(0,1,2,3,4)
  #red_toy <- data.frame("taxon1" = c(0,0,0,1,1,1), "taxon2" = c(2,3,4,2,3,4), "weight" = c(1,1,1,1,1,1))
  #red_toy

  #deg(red_toy , nodes_toy)
  # nodes   vec_deg
  #  <dbl>  <dbl>
  #   0	      3			
  #   1	      3			
  #   2 	    2			
  #   3	      2			
  #   4	      2	
  
  
  
  colnames(df) <- c("taxon1","taxon2","weight")
  df <- df[order(df[,"taxon1"]),]
  df_2 <- df[order(df[,"taxon2"]),]
  
  vec_deg <- c()
  
  
  x_1 <- 1
  x_2 <- 1
  
  for (i in 1:length(nodes)){
    suma_otu <- 0
    
    while (x_1 <= dim(df)[1] && df[x_1 , "taxon1"] == nodes[i] ){ suma_otu = suma_otu + df[x_1 ,"weight"]
  
  x_1 = x_1 + 1}
    
    while (x_2 <= dim(df)[1] && df_2[x_2 ,"taxon2"] == nodes[i] ){ suma_otu = suma_otu + df_2[x_2 ,"weight"]
  
  x_2 = x_2 + 1}
    
    vec_deg = c(vec_deg , suma_otu)
    }
    
    
  
  return(cbind.data.frame(as.data.frame(nodes),as.data.frame(vec_deg)) )
}

```

##Ejemplo de la función deg con una red más real, pero más manejable

```{r}
#example <- sample(1:7249 ,100 )
#example
#data_example <- data[example,]
#data_example <- data_example[order(data_example[,"enum"]),]
#data_example


#nodes_example <- data_example$enum
#edges_example <- c()

#for (i in 1:dim(red)[1]) {
#  if (red[i,"taxon1"] %in% nodes_example == TRUE && red[i,"taxon2"] %in% nodes_example == TRUE) {
#    edges_example = c(edges_example,i)
#  }
#}

#red_example <- red[edges_example,]
#red_example

#deg(red_example, nodes_example)
```




```{r}

nodes_toy <- c(0,1,2,3,4)
red_toy <- data.frame("taxon1" = c(0,0,0,1,1,1), "taxon2" = c(2,3,4,2,3,4), "weight" = c(1,1,1,1,1,1))
red_toy

deg(red_toy , nodes_toy)

```



```{r}


grados <- deg(red, data$nodos)
head(grados)
dim(grados)
dim(data)
```







```{r}
#Se agrega a nuestros datos el grado de los otus
data_deg <- cbind(data, grados$vec_deg)
#data_prod_deg <- cbind(data_prod ,grados$vec_deg)
#data_plan_deg <- cbind(data_plan ,grados$vec_deg)
#data_des_deg <- cbind(data_des ,grados$vec_deg)
```




```{r}
#
data_deg <- data_deg[order(data_deg[,dim(data_deg)[2]], decreasing = TRUE),]
#data_prod_deg <- data_prod_deg[order(data_prod_deg[,dim(data_prod_deg)[2]], decreasing = TRUE),]
#data_plan_deg <- data_plan_deg[order(data_plan_deg[,dim(data_plan_deg)[2]], decreasing = TRUE),]
#data_des_deg <- data_des_deg[order(data_des_deg[,dim(data_des_deg)[2]], decreasing = TRUE),]
```






```{r}
area <- auc(data_deg)
c_auc5_percent <- c()
for (x in 1:20){
  c_auc5_percent = c(c_auc5_percent,auc_percent(data_deg, (area/20)*x))
  print(auc_percent(data_deg, (area/20)*x))
}
```

##Funcion pseduo F-stat

```{r}
library(plyr)
library(vegan)
pseudo_F <- function(df , groups){
  #df es dataframe de muestras, groups, una lista de vectores de etiquetas por grupo , por grupos
  N <- dim(df)[2] #número de muestras
  a <- length(groups) #número de grupos
  
  df_groups <- list() #se crea la lista que incluirá los subdataframes por grupo
  
  for (i in 1:length(groups)){
    df_i <- df[,groups[[i]]]
    df_groups[[i]] <- df_i
  } 
  
  
  
  
  n_s <- llply( .data = df_groups , .fun = ncol )
  n_s <- unlist(n_s)
  n <- mean(n_s) #número promedio de muestras por grupo
  
  dist <- vegdist(t(df))
  dist <- as.vector(dist) #distancias bray_curtis entre todo par de muestras
  
 
  df_groups <- llply(.data = df_groups , .fun = t)
  in_dist <- llply(.data = df_groups , .fun = vegdist )
  in_dist <- llply(.data = in_dist , .fun = as.vector )
  in_dist <- unlist(in_dist) #distancias bray-curtis intra-grupo
  
  #calculo del estadistico pseudo-f
  
  ss_t <- sum(dist^2)/N 
  
  ss_w <- sum(in_dist^2)/n
  
  ss_a <- ss_t - ss_w

  f_stat <- (ss_a/(a-1))/(ss_w/(N-a))
  
  return(f_stat)
}

```



```{r}
f_stat <- c()
for (i in c_auc5_percent){
  df_i <- data_deg[1:i ,1:7]
  f_i <- pseudo_F(df_i , grupos)
  f_stat <- c(f_stat , f_i) 
  print(c(f_i ,var(f_stat)))
}
```











```{r}
nhood <- function(df, vec){
  v <- max(vec)
  nd <- vec
  i <- 1
  while (i <= dim(df)[1] && df[i,1] != v){
    if (is.element(df[i,1] , vec) == TRUE && is.element(df[i,2] , vec) == TRUE  ){
      i <- i + 1
    } else { if (is.element(df[i,1] , vec) == TRUE && is.element(df[i,2] , nd) == FALSE  ) {
      nd <- c(nd, df[i,2])
    }
      if (is.element(df[i,2] , vec) == TRUE && is.element(df[i,1] , nd) == FALSE) {
      nd <- c(nd, df[i,1])
    }
      i <- i + 1  }
      }
  
  while (i <= dim(df)[1] && df[i,1] == v){
    nd <- c(nd , df[i,2])
    i <- i + 1
  }
  
  
  
  return(nd)
}
```



```{r}
nhood(red , c(1,9,300))

```


```{r}
distan <- function(df , nodes , u , v){
  #u_0 <- min(c(u,v))
  #u_1 <- max(c(u,v))
  i <- 0
  nd_0 <- c(u)
  while( is.element(v , nd_0) == FALSE && i <=  length(nodes) ){
    nd_0 <- nhood(df , nd_0)
    i <- i + 1  
    }
  
  return(i)
}
```


```{r}
distan(red, otus,4000 ,0)
```



```{r}
paths_min <- function(df, nodes, u , v) {
  list_uv <- list(u)
  list_vu <- list(v)
  x_1 <- 1
  x_2 <- 2
  
  while (is.element(v, list_uv[[x_1]]) == FALSE && x_1 <= length(nodes) ) {
    
    list_uv[[x_1 + 1]] <- nhood(df , list_uv[[x_1]] )
    
    x_1 = x_1 + 1
  
    }
  
  while (is.element(v, list_uv[[x_2]]) == FALSE && x_2 <= length(nodes) ) {
    
    list_uv[[x_2 + 1]] <- nhood(df , list_uv[[x_2]] )
    
    x_2 = x_2 + 1
  
    }
  
  
  
}



```





